= `@independent` annotation

The `@independent` annotation is used
// tag::overview[]
to prevent attributes without owners from being deleted automatically.
// end::overview[]

== Syntax

.Syntax
[,typeql]
----
<type label> @independent;
----

The `@independent` annotation does not accept any arguments.

== Usage

// tag::description[]
The `@independent` annotation enforces the `independent` constraint for an attribute type, allowing instances of the type to exist independently of their owner.
// end::description[]

// TODO: Add a reference to attributes and their dependency on existing owners

By default, attributes (instances of attribute types) depend on their owners. Such attributes:
* cannot be inserted without a `has` clause.
* are automatically deleted when all their owners have been deleted.

In contrast, attributes of independent types can exist without owners.

.Independent attribute types definition
[,typeql]
----
include::{page-version}@typeql::example$tql/schema_annotations.tql[tags=define-keyword;independent-attribute;]
----

.Independent attributes insertion
[,typeql]
----
include::{page-version}@typeql::example$tql/data_annotations.tql[tags=insert-keyword;independent-attribute;]
----

=== Subtyping

The `independent` constraint is inherited. This means that all subtypes of an independent type are also independent, and it cannot be changed.
